import numpy as np
import pandas as pd

def metrics(equity:pd.DataFrame,trades:pd.DataFrame,initial:float)->dict:
    if equity.empty:return {"Starting Capital":initial,"Ending Capital":initial}
    e=equity.copy();e["date"]=pd.to_datetime(e.date);eq=e.equity.astype(float);daily=eq.pct_change().fillna(0);years=max((e.date.iloc[-1]-e.date.iloc[0]).days/365.25,1/365.25);dd=eq/eq.cummax()-1;down=daily[daily<0].std();avg_eq=eq.mean()
    out={"Starting Capital":initial,"Ending Capital":eq.iloc[-1],"Total Return":eq.iloc[-1]/initial-1,"CAGR":(eq.iloc[-1]/initial)**(1/years)-1,"Max Drawdown":dd.min(),"Average Drawdown":dd[dd<0].mean() if (dd<0).any() else 0.,"Sharpe Ratio":np.sqrt(252)*daily.mean()/daily.std() if daily.std() else 0.,"Sortino Ratio":np.sqrt(252)*daily.mean()/down if down else 0.,"Capital Utilization":e.invested.sum()/eq.sum() if eq.sum() else 0.,"Time in Market":e.positions.gt(0).mean(),"Average Cash %":(e.cash/eq).mean(),"Average Positions":e.positions.mean(),"Maximum Concurrent Positions":int(e.positions.max())}
    zero=["Win Rate","Profit Factor","Average Trade Return","Median Trade Return","Expectancy per trade","Expectancy per capital day","Expected log return","Average Holding Days","Median Holding Days","Trades Per Year","Best Trade","Worst Trade","Average MAE","Median MAE","Worst-decile MAE","Average MFE","Median MFE","Take Profit Hit Rate","Thesis Break Exit Rate","Time Exit Rate","Median Days to TP","Percentage Never Reaching TP","Portfolio Turnover","Worst 1%","Worst 5%","CVaR 5%","Largest Single Trade Loss","Top 1 Trade Contribution","Top 5 Trade Contribution","Top Symbol Contribution","Top 5 Symbols Contribution","Best Year Contribution"]
    if trades.empty:out.update({k:0. for k in zero});return out
    t=trades.copy();wins=t.loc[t.net_pnl>0,"net_pnl"].sum();losses=-t.loc[t.net_pnl<0,"net_pnl"].sum();tp=t.exit_reason.isin(["TP","TAKE_PROFIT"]);ret=t.return_pct.astype(float);holding=t.holding_days.clip(lower=1);total_profit=t.net_pnl.sum();by_symbol=t.groupby("symbol").net_pnl.sum().sort_values(ascending=False);year=t.assign(year=pd.to_datetime(t.exit_date).dt.year).groupby("year").net_pnl.sum().sort_values(ascending=False)
    loss_tail=ret[ret<=ret.quantile(.05)];gross_turnover=((t.entry_price*t.quantity).sum()+(t.exit_price*t.quantity).sum())
    out.update({"Win Rate":(t.net_pnl>0).mean(),"Profit Factor":wins/losses if losses else float("inf"),"Average Trade Return":ret.mean(),"Median Trade Return":ret.median(),"Expectancy per trade":ret.mean(),"Expectancy per capital day":ret.sum()/holding.sum(),"Expected log return":np.log1p(ret.clip(lower=-.999)).mean(),"Average Holding Days":holding.mean(),"Median Holding Days":holding.median(),"Trades Per Year":len(t)/years,"Best Trade":ret.max(),"Worst Trade":ret.min(),"Average MAE":t.mae.mean(),"Median MAE":t.mae.median(),"Worst-decile MAE":t.mae.quantile(.10),"Average MFE":t.mfe.mean(),"Median MFE":t.mfe.median(),"Take Profit Hit Rate":tp.mean(),"Thesis Break Exit Rate":t.exit_reason.eq("THESIS_BREAK").mean(),"Time Exit Rate":t.exit_reason.eq("TIME_EXIT").mean(),"Median Days to TP":holding[tp].median() if tp.any() else 0.,"Percentage Never Reaching TP":1-tp.mean(),"Portfolio Turnover":gross_turnover/(avg_eq*years) if avg_eq else 0.,"Worst 1%":ret.quantile(.01),"Worst 5%":ret.quantile(.05),"CVaR 5%":loss_tail.mean() if len(loss_tail) else 0.,"Largest Single Trade Loss":ret.min(),"Top 1 Trade Contribution":t.net_pnl.nlargest(1).sum()/total_profit if total_profit else np.nan,"Top 5 Trade Contribution":t.net_pnl.nlargest(5).sum()/total_profit if total_profit else np.nan,"Top Symbol Contribution":by_symbol.head(1).sum()/total_profit if total_profit else np.nan,"Top 5 Symbols Contribution":by_symbol.head(5).sum()/total_profit if total_profit else np.nan,"Best Year Contribution":year.head(1).sum()/total_profit if total_profit else np.nan})
    return out
