from abc import ABC,abstractmethod
class Broker(ABC):
    @abstractmethod
    def get_cash(self):...
    @abstractmethod
    def get_settlements(self):...
    @abstractmethod
    def get_positions(self):...
    @abstractmethod
    def get_open_orders(self):...
    @abstractmethod
    def place_buy(self,symbol,quantity,price,client_order_id):...
    @abstractmethod
    def place_sell(self,symbol,quantity,price,client_order_id):...
    @abstractmethod
    def cancel_order(self,order_id):...
    @abstractmethod
    def get_order_status(self,order_id):...

